### ISSUE TITLE
windows build fails, 

### ISSUE THREAD

**Issue by AnttiLukats** [michaelcmartin/Ophis#31]
X:\GIT\Ophis\src>python win_setup.py
running py2exe
running build_py
creating build
creating build\lib
creating build\lib\Ophis
copying Ophis\CmdLine.py -> build\lib\Ophis
copying Ophis\CorePragmas.py -> build\lib\Ophis
copying Ophis\Environment.py -> build\lib\Ophis
copying Ophis\Errors.py -> build\lib\Ophis
copying Ophis\Frontend.py -> build\lib\Ophis
copying Ophis\IR.py -> build\lib\Ophis
copying Ophis\Listing.py -> build\lib\Ophis
copying Ophis\Macro.py -> build\lib\Ophis
copying Ophis\Main.py -> build\lib\Ophis
copying Ophis\Opcodes.py -> build\lib\Ophis
copying Ophis\Passes.py -> build\lib\Ophis
copying Ophis\__init__.py -> build\lib\Ophis
Traceback (most recent call last):
  File "win_setup.py", line 10, in <module>
    console=[{'script': "scripts/ophis"}])
  File "C:\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Python37\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Python37\lib\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Python37\lib\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range

**Comment by michaelcmartin** [comment]
This is most likely part of a broader issue involving packaging. Ophis is a very old project and hasn't really kept up with the modern tooling for the production of packages and the like, even off of Windows. One of the goals for the next release will be proper integration with PyPI; as part of this, py2exe support will need to be upgraded as well.

**Comment by michaelcmartin** [comment]
Folding this into Issue #35
